# Generated by Django 3.2.3 on 2021-05-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=15)),
                ('password', models.IntegerField(default=8)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
